catalog:
  "@changesets/changelog-github": 0.7.0
  "@changesets/cli": 2.31.0
  "@rune-cli/rune": 0.3.2
  "@types/node": 24.12.4
  "@typescript/native-preview": 7.0.0-dev.20260506.1
  typescript: 6.0.3
  vite: 8.0.10
  vite-plus: 0.1.21
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
